### ISSUE TITLE
Download link to only thumbnail

### ISSUE THREAD

**Issue by Fakhrillo** [CrypticGuy/pyigdl#1] opened 2024-08-19 10:25 UTC
Hey there, I saw your work, that's great, but I couldn't use it to download Instagram videos, instead, it's giving download links to the thumbnail only, if you can fix that part it would be very great, thanks.

**Comment by CrypticGuy** [comment] 2024-08-21 06:45
Looking into this. Can you share some urls that are not working? Will attempt to fix it today.

**Comment by CrypticGuy** [comment] 2024-08-21 15:13
Hey @Fakhrillo , try now, patched it. Let me know if you still face any issue.

Will look into an improved solution in near future.

**Comment by amiteshore** [comment] 2024-08-24 06:15
Hey @CrypticGuy , love your work.

I’m encountering an issue with the `IGDownloader` function from `pyigdl`. When running the following code:

```py
from pyigdl import IGDownloader

data = IGDownloader("https://www.instagram.com/p/C_B03_ry0aK/?utm_source=ig_web_copy_link")
# print(data[0]["download_link"])
print(data)
```

I noticed that the `thumbnail_link` values are not returned correctly after the first three items. It returns `thumbnail_link': '/imgs/loader.gif`, whereas `download_link` is returned correctly.

I'm including the response in JSON format:

<details>
  <summary>Click to see the JSON response</summary>
  
```json
[
  {
    "download_link": "https://dl.snapcdn.app/download?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJodHRwczovL3Njb250ZW50LmNkbmluc3RhZ3JhbS5jb20vdi90NTEuMjkzNTAtMTUvNDU2NTcyMjY3XzM3NzA5MTMyMTk4MzEyOTZfMTMxOTk1NDgyOTM3MjE1NjYyOV9uLmpwZz9zdHA9ZHN0LWpwZ19lMzVfcDEwODB4MTA4MCZlZmc9ZXlKMlpXNWpiMlJsWDNSaFp5STZJbWx0WVdkbFgzVnliR2RsYmk0eE5EUXdlREU0TURBdWMyUnlMbVl5T1RNMU1DNWtaV1poZFd4MFgybHRZV2RsSW4wJl9uY19odD1zY29udGVudC1oZWwzLTEuY2RuaW5zdGFncmFtLmNvbSZfbmNfY2F0PTEmX25jX29oYz1hOEZjamlFUGp4WVE3a052Z0hxVUlzNSZlZG09QVBfVjEwRUJBQUFBJmNjYj03LTUmb2g9MDBfQVlCU2lhcDdJd254VmVhS0JqdDBZZkFtbFByV3Znd2JLOEx5U1N4Zno3d2k1dyZvZT02NkNGMzFCNCZfbmNfc2lkPTI5OTliOCIsImZpbGVuYW1lIjoiU2F2ZUlHLkFwcF80NTY1NzIyNjdfMzc3MDkxMzIxOTgzMTI5Nl8xMzE5OTU0ODI5MzcyMTU2NjI5X24uanBnIiwibmJmIjoxNzI0NDc5NzI4LCJleHAiOjE3MjQ0ODMzMjgsImlhdCI6MTcyNDQ3OTcyOH0.sbqajmzNnLvQd9LW4cQ-tIws1oQJ1zMzfxaMT65xhHI",
    "thumbnail_link": "https://i.snapcdn.app/photo?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJodHRwczovL3Njb250ZW50LmNkbmluc3RhZ3JhbS5jb20vdi90NTEuMjkzNTAtMTUvNDU2NTcyMjY3XzM3NzA5MTMyMTk4MzEyOTZfMTMxOTk1NDgyOTM3MjE1NjYyOV9uLmpwZz9zdHA9ZHN0LWpwZ19lMzVfcDY0MHg2NDBfc2gwLjA4JmVmZz1leUoyWlc1amIyUmxYM1JoWnlJNkltbHRZV2RsWDNWeWJHZGxiaTR4TkRRd2VERTRNREF1YzJSeUxtWXlPVE0xTUM1a1pXWmhkV3gwWDJsdFlXZGxJbjAmX25jX2h0PXNjb250ZW50LWhlbDMtMS5jZG5pbnN0YWdyYW0uY29tJl9uY19jYXQ9MSZfbmNfb2hjPWE4RmNqaUVQanhZUTdrTnZnSHFVSXM1JmVkbT1BUF9WMTBFQkFBQUEmY2NiPTctNSZvaD0wMF9BWUJseTZVMGJxclVBME9kamxHUUVzZC0yck1KN21SUGtHLWpGZ2JtSWlrUkhBJm9lPTY2Q0YzMUI0Jl9uY19zaWQ9Mjk5OWI4IiwiZmlsZW5hbWUiOiJUaHVtYm5haWxfNDU2NTcyMjY3XzM3NzA5MTMyMTk4MzEyOTZfMTMxOTk1NDgyOTM3MjE1NjYyOV9uLmpwZyIsIm5iZiI6MTcyNDQ3OTcyOCwiZXhwIjoxNzI0NDgzMzI4LCJpYXQiOjE3MjQ0Nzk3Mjh9.by1G2e8jYt9Cea0Cs5DkE7NQ4J3CBkOa_mg403pN1y0"
  },
  {
    "download_link": "https://dl.snapcdn.app/download?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJodHRwczovL3Njb250ZW50LmNkbmluc3RhZ3JhbS5jb20vdi90NTEuMjkzNTAtMTUvNDU2NTQ4OTA3XzQ3Mzc1OTIxNTU2MzA3MV82MDQ0ODI4MzEyMDAwNzMwNDc4X24uanBnP3N0cD1kc3QtanBnX2UzNV9wMTA4MHgxMDgwJmVmZz1leUoyWlc1amIyUmxYM1JoWnlJNkltbHRZV2RsWDNWeWJHZGxiaTR4TkRRd2VERTRNREF1YzJSeUxtWXlPVE0xTUM1a1pXWmhkV3gwWDJsdFlXZGxJbjAmX25jX2h0PXNjb250ZW50LWhlbDMtMS5jZG5pbnN0YWdyYW0uY29tJl9uY19jYXQ9MSZfbmNfb2hjPWs1SzdScHBPVjdvUTdrTnZnSHRnXzF6JmVkbT1BUF9WMTBFQkFBQUEmY2NiPTctNSZvaD0wMF9BWURFR2c3NElad2Qyb0R2cldlbGNJSjdtcmhEWnpib1A4STNMcUtLVDR1bnR3Jm9lPTY2Q0YyNENCJl9uY19zaWQ9Mjk5OWI4IiwiZmlsZW5hbWUiOiJTYXZlSUcuQXBwXzQ1NjU0ODkwN180NzM3NTkyMTU1NjMwNzFfNjA0NDgyODMxMjAwMDczMDQ3OF9uLmpwZyIsIm5iZiI6MTcyNDQ3OTcyOCwiZXhwIjoxNzI0NDgzMzI4LCJpYXQiOjE3MjQ0Nzk3Mjh9.kmFd16YYXDUaP_UsM5tKo4suDD5DjEcpjLAIGGtOmlw",
    "thumbnail_link": "https://i.snapcdn.app/photo?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJodHRwczovL3Njb250ZW50LmNkbmluc3RhZ3JhbS5jb20vdi90NTEuMjkzNTAtMTUvNDU2NTQ4OTA3XzQ3Mzc1OTIxNTU2MzA3MV82MDQ0ODI4MzEyMDAwNzMwNDc4X24uanBnP3N0cD1kc3QtanBnX2UzNV9wNjQweDY0MF9zaDAuMDgmZWZnPWV5SjJaVzVqYjJSbFgzUmhaeUk2SW1sdFlXZGxYM1Z5YkdkbGJpNHhORFF3ZURFNE1EQXVjMlJ5TG1ZeU9UTTFNQzVrWldaaGRXeDBYMmx0WVdkbEluMCZfbmNfaHQ9c2NvbnRlbnQtaGVsMy0xLmNkbmluc3RhZ3JhbS5jb20mX25jX2NhdD0xJl9uY19vaGM9azVLN1JwcE9WN29RN2tOdmdIdGdfMXomZWRtPUFQX1YxMEVCQUFBQSZjY2I9Ny01Jm9oPTAwX0FZQjJGd21iQ0Y0NThNQ0xIVUVtVzNRVFp1OVRBcG9iRzFGZXkzN3VRN29YWmcmb2U9NjZDRjI0Q0ImX25jX3NpZD0yOTk5YjgiLCJmaWxlbmFtZSI6IlRodW1ibmFpbF80NTY1NDg5MDdfNDczNzU5MjE1NTYzMDcxXzYwNDQ4MjgzMTIwMDA3MzA0Nzhfbi5qcGciLCJuYmYiOjE3MjQ0Nzk3MjgsImV4cCI6MTcyNDQ4MzMyOCwiaWF0IjoxNzI0NDc5NzI4fQ.M3X1XohGA_sgPp0M7Rw9I3Sae6qQus2QazvIXuq7KFU"
  },
  {
    "download_link": "https://dl.snapcdn.app/download?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJodHRwczovL3Njb250ZW50LmNkbmluc3RhZ3JhbS5jb20vdi90NTEuMjkzNTAtMTUvNDU2ODg3NzAwXzgwOTg2MDIwMTM0NjA1MV84NDMyMzExMjI1ODcyMDIwMTkwX24uanBnP3N0cD1kc3QtanBnX2UzNV9wMTA4MHgxMDgwJmVmZz1leUoyWlc1amIyUmxYM1JoWnlJNkltbHRZV2RsWDNWeWJHZGxiaTR4TkRRd2VERTRNREF1YzJSeUxtWXlPVE0xTUM1a1pXWmhkV3gwWDJsdFlXZGxJbjAmX25jX2h0PXNjb250ZW50LWhlbDMtMS5jZG5pbnN0YWdyYW0uY29tJl9uY19jYXQ9MSZfbmNfb2hjPXd0d195UnMyVjVrUTdrTnZnRnI0MExXJl9uY19naWQ9ZmE5ZDdiM2IzMjJkNGVkZmFlZDRlMjMyNTg0N2ZiYzcmZWRtPUFQX1YxMEVCQUFBQSZjY2I9Ny01Jm9oPTAwX0FZQjVQYlU2X2E1NjVBYkVPS2lxeF9oVGZNeElyam9VT3RyVG5IOC1LZkwxY3cmb2U9NjZDRjRDMEQmX25jX3NpZD0yOTk5YjgiLCJmaWxlbmFtZSI6IlNhdmVJRy5BcHBfNDU2ODg3NzAwXzgwOTg2MDIwMTM0NjA1MV84NDMyMzExMjI1ODcyMDIwMTkwX24uanBnIiwibmJmIjoxNzI0NDc5NzI4LCJleHAiOjE3MjQ0ODMzMjgsImlhdCI6MTcyNDQ3OTcyOH0.hAQ8jKKOh1Kyzn2JlNbLIwGo0orSUERPMf6t7HJu9cY",
    "thumbnail_link": "https://i.snapcdn.app/photo?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJodHRwczovL3Njb250ZW50LmNkbmluc3RhZ3JhbS5jb20vdi90NTEuMjkzNTAtMTUvNDU2ODg3NzAwXzgwOTg2MDIwMTM0NjA1MV84NDMyMzExMjI1ODcyMDIwMTkwX24uanBnP3N0cD1kc3QtanBnX2UzNV9wNjQweDY0MF9zaDAuMDgmZWZnPWV5SjJaVzVqYjJSbFgzUmhaeUk2SW1sdFlXZGxYM1Z5YkdkbGJpNHhORFF3ZURFNE1EQXVjMlJ5TG1ZeU9UTTFNQzVrWldaaGRXeDBYMmx0WVdkbEluMCZfbmNfaHQ9c2NvbnRlbnQtaGVsMy0xLmNkbmluc3RhZ3JhbS5jb20mX25jX2NhdD0xJl9uY19vaGM9d3R3X3lSczJWNWtRN2tOdmdGcjQwTFcmZWRtPUFQX1YxMEVCQUFBQSZjY2I9Ny01Jm9oPTAwX0FZQW1IWnRIbGJpdm54OTZ6dUozZk03UWZMdUxpamNVbTRRMXprQVlSdzVDOVEmb2U9NjZDRjRDMEQmX25jX3NpZD0yOTk5YjgiLCJmaWxlbmFtZSI6IlRodW1ibmFpbF80NTY4ODc3MDBfODA5ODYwMjAxMzQ2MDUxXzg0MzIzMTEyMjU4NzIwMjAxOTBfbi5qcGciLCJuYmYiOjE3MjQ0Nzk3MjgsImV4cCI6MTcyNDQ4MzMyOCwiaWF0IjoxNzI0NDc5NzI4fQ.16QHgEqrZwkPi1VKIF3DpZFHYNbF87qv8TPu1FekWGc"
  },
  {
    "download_link": "https://dl.snapcdn.app/download?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJodHRwczovL3Njb250ZW50LmNkbmluc3RhZ3JhbS5jb20vdi90NTEuMjkzNTAtMTUvNDU2NjIyNTcwXzIzMjYzNDQ3NTEwNDg0NzZfMzQwODE0MjgzNDIxNDc5MzExMl9uLmpwZz9zdHA9ZHN0LWpwZ19lMzVfcDEwODB4MTA4MCZlZmc9ZXlKMlpXNWpiMlJsWDNSaFp5STZJbWx0WVdkbFgzVnliR2RsYmk0eE5EUXdlREU0TURBdWMyUnlMbVl5T1RNMU1DNWtaV1poZFd4MFgybHRZV2RsSW4wJl9uY19odD1zY29udGVudC1oZWwzLTEuY2RuaW5zdGFncmFtLmNvbSZfbmNfY2F0PTEwMCZfbmNfb2hjPVh4WGVlcnlpSTRNUTdrTnZnRUhlQmJjJmVkbT1BUF9WMTBFQkFBQUEmY2NiPTctNSZvaD0wMF9BWUJBYXpJU2ZCUnpvb01WWFlXbHhDeUoxbGJETUJnWXJqdmo5V0pZN0hlVDhnJm9lPTY2Q0YzMDI2Jl9uY19zaWQ9Mjk5OWI4IiwiZmlsZW5hbWUiOiJTYXZlSUcuQXBwXzQ1NjYyMjU3MF8yMzI2MzQ0NzUxMDQ4NDc2XzM0MDgxNDI4MzQyMTQ3OTMxMTJfbi5qcGciLCJuYmYiOjE3MjQ0Nzk3MjgsImV4cCI6MTcyNDQ4MzMyOCwiaWF0IjoxNzI0NDc5NzI4fQ.5O-oUaGmfxH_NQn--U4P41Q4kAz-DluLSe3n0gQUJPI",
    "thumbnail_link": "/imgs/loader.gif"
  },
  {
    "download_link": "https://dl.snapcdn.app/download?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJodHRwczovL3Njb250ZW50LmNkbmluc3RhZ3JhbS5jb20vdi90NTEuMjkzNTAtMTUvNDU2OTA3NDEzXzEwMjIyNDk0NjI2ODM0NzJfNDQxNzI4OTA3MjkzNTEyMzc1Nl9uLmpwZz9zdHA9ZHN0LWpwZ19lMzVfcDEwODB4MTA4MCZlZmc9ZXlKMlpXNWpiMlJsWDNSaFp5STZJbWx0WVdkbFgzVnliR2RsYmk0eE5EUXdlREU0TURBdWMyUnlMbVl5T1RNMU1DNWtaV1poZFd4MFgybHRZV2RsSW4wJl9uY19odD1zY29udGVudC1oZWwzLTEuY2RuaW5zdGFncmFtLmNvbSZfbmNfY2F0PTEwOCZfbmNfb2hjPU04UmFadkJwd1dzUTdrTnZnSENnbmctJmVkbT1BUF9WMTBFQkFBQUEmY2NiPTctNSZvaD0wMF9BWURRSWF1NmVFelg5eTZsOU00bGxpYTV2S3VLa0dRcklablozeXZUbTdhU1ZRJm9lPTY2Q0YzQUJCJl9uY19zaWQ9Mjk5OWI4IiwiZmlsZW5hbWUiOiJTYXZlSUcuQXBwXzQ1NjkwNzQxM18xMDIyMjQ5NDYyNjgzNDcyXzQ0MTcyODkwNzI5MzUxMjM3NTZfbi5qcGciLCJuYmYiOjE3MjQ0Nzk3MjgsImV4cCI6MTcyNDQ4MzMyOCwiaWF0IjoxNzI0NDc5NzI4fQ.2lQGkFew9wDi0DQWqV4jraif_gAlCM93D-FidxdRf7k",
    "thumbnail_link": "/imgs/loader.gif"
  },
  {
    "download_link": "https://dl.snapcdn.app/download?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJodHRwczovL3Njb250ZW50LmNkbmluc3RhZ3JhbS5jb20vdi90NTEuMjkzNTAtMTUvNDU2NDYwNDM5XzExNzcxNzU1NzMzNDc1MDhfNDE2MTc1OTMwNjY3OTk1Mjk2NF9uLmpwZz9zdHA9ZHN0LWpwZ19lMzVfcDEwODB4MTA4MCZlZmc9ZXlKMlpXNWpiMlJsWDNSaFp5STZJbWx0WVdkbFgzVnliR2RsYmk0eE5EUXdlREU0TURBdWMyUnlMbVl5T1RNMU1DNWtaV1poZFd4MFgybHRZV2RsSW4wJl9uY19odD1zY29udGVudC1oZWwzLTEuY2RuaW5zdGFncmFtLmNvbSZfbmNfY2F0PTEwOCZfbmNfb2hjPWtpRi1NOHB4R3g4UTdrTnZnRkZueTRHJmVkbT1BUF9WMTBFQkFBQUEmY2NiPTctNSZvaD0wMF9BWURudnhXNU55TUNIN0wtcjRkQ3JRMUx3Nldldkl0dHUzaG5TNENSdFdaNmVBJm9lPTY2Q0YzMjA2Jl9uY19zaWQ9Mjk5OWI4IiwiZmlsZW5hbWUiOiJTYXZlSUcuQXBwXzQ1NjQ2MDQzOV8xMTc3MTc1NTczMzQ3NTA4XzQxNjE3NTkzMDY2Nzk5NTI5NjRfbi5qcGciLCJuYmYiOjE3MjQ0Nzk3MjgsImV4cCI6MTcyNDQ4MzMyOCwiaWF0IjoxNzI0NDc5NzI4fQ.lNnAqGIPXp3xCMx9HEg2pq0orhm08McP5jkF-lO6yQM",
    "thumbnail_link": "/imgs/loader.gif"
  },
  {
    "download_link": "https://dl.snapcdn.app/download?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJodHRwczovL3Njb250ZW50LmNkbmluc3RhZ3JhbS5jb20vdi90NTEuMjkzNTAtMTUvNDU2ODY2ODA2XzgxNTkwNTYzNzQxODEyM184MjI5NTYwNzkwNjU3NzEzMDcyX24uanBnP3N0cD1kc3QtanBnX2UzNV9wMTA4MHgxMDgwJmVmZz1leUoyWlc1amIyUmxYM1JoWnlJNkltbHRZV2RsWDNWeWJHZGxiaTR4TkRRd2VERTRNREF1YzJSeUxtWXlPVE0xTUM1a1pXWmhkV3gwWDJsdFlXZGxJbjAmX25jX2h0PXNjb250ZW50LWhlbDMtMS5jZG5pbnN0YWdyYW0uY29tJl9uY19jYXQ9MTAzJl9uY19vaGM9OUZTY2UtSUUyT2tRN2tOdmdIVkUwWFcmZWRtPUFQX1YxMEVCQUFBQSZjY2I9Ny01Jm9oPTAwX0FZQ1RqbHMtelBYUjNOWFdSZWRKV0thY3BtMUt4V1pXR0ktUGstV3lfY2hCU3cmb2U9NjZDRjNDRDQmX25jX3NpZD0yOTk5YjgiLCJmaWxlbmFtZSI6IlNhdmVJRy5BcHBfNDU2ODY2ODA2XzgxNTkwNTYzNzQxODEyM184MjI5NTYwNzkwNjU3NzEzMDcyX24uanBnIiwibmJmIjoxNzI0NDc5NzI4LCJleHAiOjE3MjQ0ODMzMjgsImlhdCI6MTcyNDQ3OTcyOH0.YNlWQ0C1GBMVdDnoCoVnUCjZZc8BclwJsiMhlv999os",
    "thumbnail_link": "/imgs/loader.gif"
  },
  {
    "download_link": "https://dl.snapcdn.app/download?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJodHRwczovL3Njb250ZW50LmNkbmluc3RhZ3JhbS5jb20vdi90NTEuMjkzNTAtMTUvNDU2MzkxMDU3XzQyNjExNzc2Mzc4NzY3NF8yOTI3NTYxODAwMTc0OTAzMDQ1X24uanBnP3N0cD1kc3QtanBnX2UzNV9wMTA4MHgxMDgwJmVmZz1leUoyWlc1amIyUmxYM1JoWnlJNkltbHRZV2RsWDNWeWJHZGxiaTR4TkRRd2VERTRNREF1YzJSeUxtWXlPVE0xTUM1a1pXWmhkV3gwWDJsdFlXZGxJbjAmX25jX2h0PXNjb250ZW50LWhlbDMtMS5jZG5pbnN0YWdyYW0uY29tJl9uY19jYXQ9MTEwJl9uY19vaGM9ZWc5bmFqTEUyYUFRN2tOdmdFVUhVVXAmZWRtPUFQX1YxMEVCQUFBQSZjY2I9Ny01Jm9oPTAwX0FZQ24tVGt5R0dsUjNuLUhlX0VRalJsTUVCVlJQdUcwZDdwVDNXNXhRdHRhM3cmb2U9NjZDRjI0QjAmX25jX3NpZD0yOTk5YjgiLCJmaWxlbmFtZSI6IlNhdmVJRy5BcHBfNDU2MzkxMDU3XzQyNjExNzc2Mzc4NzY3NF8yOTI3NTYxODAwMTc0OTAzMDQ1X24uanBnIiwibmJmIjoxNzI0NDc5NzI4LCJleHAiOjE3MjQ0ODMzMjgsImlhdCI6MTcyNDQ3OTcyOH0.dd71v6fELPoBS5D6wFRod04eFl6VWjYTwfg3c2coWOg",
    "thumbnail_link": "/imgs/loader.gif"
  },
  {
    "download_link": "https://dl.snapcdn.app/download?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJodHRwczovL3Njb250ZW50LmNkbmluc3RhZ3JhbS5jb20vdi90NTEuMjkzNTAtMTUvNDU3MDE3MzM4XzgxODgzMTYzNzA3NzkxMV84ODk3Nzg5OTIzODk1ODI0MDI3X24uanBnP3N0cD1kc3QtanBnX2UzNV9wMTA4MHgxMDgwJmVmZz1leUoyWlc1amIyUmxYM1JoWnlJNkltbHRZV2RsWDNWeWJHZGxiaTR4TkRRd2VERTRNREF1YzJSeUxtWXlPVE0xTUM1a1pXWmhkV3gwWDJsdFlXZGxJbjAmX25jX2h0PXNjb250ZW50LWhlbDMtMS5jZG5pbnN0YWdyYW0uY29tJl9uY19jYXQ9MTA3Jl9uY19vaGM9WkdzNkVOZWdndmNRN2tOdmdIbkpVS28mZWRtPUFQX1YxMEVCQUFBQSZjY2I9Ny01Jm9oPTAwX0FZQmJFVzI1YlE3dUcyR2RyN1owMXRPLWpoRUM5Vl9EanVzTHlrZFI2VDBrRncmb2U9NjZDRjMwMkEmX25jX3NpZD0yOTk5YjgiLCJmaWxlbmFtZSI6IlNhdmVJRy5BcHBfNDU3MDE3MzM4XzgxODgzMTYzNzA3NzkxMV84ODk3Nzg5OTIzODk1ODI0MDI3X24uanBnIiwibmJmIjoxNzI0NDc5NzI4LCJleHAiOjE3MjQ0ODMzMjgsImlhdCI6MTcyNDQ3OTcyOH0.c-wGm6zwWKzGqHOy-QUmgj9GEhLpO5n3jRhCIsrRPq0",
    "thumbnail_link": "/imgs/loader.gif"
  }
]
```
</details>

Is there a known issue or limitation with the `IGDownloader` function that could explain this behavior?

I appreciate your help in resolving this issue. Thank you!

**Comment by CrypticGuy** [comment] 2024-08-24 06:28
Hey @amiteshore , looking into this. Is this like one of those carousel posts? I haven't evaluated those yet, but I'll check this and get back.

**Comment by amiteshore** [comment] 2024-08-24 08:44
@CrypticGuy Yes, the issue I'm describing occurs specifically with carousel posts.

The `IGDownloader` function works correctly for single photos or reels. However, when handling links that contain multiple posts (such as carousel posts), it seems to encounter problems, leading to incorrect `thumbnail_link` values after the initial items.

**Comment by CrypticGuy** [comment] 2024-08-24 08:47
Sure. Will check it out and see what the issue is.

**Comment by CrypticGuy** [comment] 2024-08-25 11:41
Hey @amiteshore , try running it now. Made some patches to support carousel downloads. It should work now.

**Comment by amiteshore** [comment] 2024-08-25 15:36
Hi @CrypticGuy,

Thanks for the quick update! The changes you made have indeed resolved the issues with carousel posts—they are now working as expected.

However, I've encountered a new issue with single photo posts. Here’s the test code I used:

```python
from pyigdl import IGDownloader
import json

# data = IGDownloader("https://www.instagram.com/p/C-VlefaxDc9") # Carousel, works
# data = IGDownloader("https://www.instagram.com/reel/C-TIiK4y7_w") # Reel, works
data = IGDownloader("https://www.instagram.com/p/C-5szP6xjoC") # Single photo, doesn't work

formatted_data = json.dumps(data, indent=4, sort_keys=True)
print(formatted_data)
```

When attempting to download a single photo, I get the following error:

```
Traceback (most recent call last):
  File "/home/username/exp/downloader/venv/lib/python3.12/site-packages/pyigdl/igdl.py", line 59, in IGDownloader
    return _sendPostRequest(serverUrl, payloadData, headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/exp/downloader/venv/lib/python3.12/site-packages/pyigdl/igdl.py", line 52, in _sendPostRequest
    return _parseResponse(response)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/exp/downloader/venv/lib/python3.12/site-packages/pyigdl/igdl.py", line 42, in _parseResponse
    "download_link": elem.css(".download-items__btn > a").attrib["href"]
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'href'
```

Additionally, during the error handling, another issue occurred:

```
TypeError: BaseException.with_traceback() takes exactly one argument (0 given)
```

It seems there’s a problem specifically with handling single photo posts. Could you please take a look at this?

Thanks again for your time!

**Comment by CrypticGuy** [comment] 2024-08-25 17:20
Resolving the issue as the original query has been addressed. Creating new issue for photos download url.

**Closed by CrypticGuy** 2024-08-25 17:20 UTC
Labels: bug, enhancement
